### ISSUE TITLE
GEOS: Useful to implement the core functionalities?

### ISSUE THREAD

**Issue by Rauldg** [envire/envire-core#1]
I start this thread to analyse how compatible are the functionalities that [GEOS] provides with what we are developing in Envire, and more specifically in the core.

[GEOS]: http://trac.osgeo.org/geos/

**Comment by saarnold** [comment]
It seems to me that GEOS doesn't have any concept for frames or transformations. Since our geometry objects would be alligned to differnet frames we would need to create a new geometry in the frame of the other before we can perform operations on them. Or did I miss something?

**Comment by jhidalgocarrio** [comment]
GEOS is to ask and establish spatial relationship in already defined maps. The data to use must be in GIS maps format and therefore the GDAL library needs to be used before GEOS.
IMO the working pipeline will be: Envire (Tree) -> GDAL -> GEOS

**Comment by Rauldg** [comment]
I would leave GEOS and GDAL outside of the core but definitely integrate them in a plugin.

![envire-gis](https://cloud.githubusercontent.com/assets/8087995/8480142/6b62efb8-20dc-11e5-868d-46c215c764bb.png)

**Comment by saarnold** [comment]
Yes, this should be the setup when we talk about storing map information inside a DB. [GRASS](http://grass.osgeo.org/documentation/general-overview/) could be also a good alternative to GEOS here.
But the current use-case is handling of transformations (frames) and boundary information of items only.
